### ISSUE TITLE
The use of the word "parser" is misleading

### ISSUE THREAD

**Issue by wytsai7660** [PinkNekoFist/bad_apple#3]
`image_parser()` and `ascii_parser()` are not actually "parsing" anything; `image_parser()` is to extract frames from a video, and `ascii_parser()` is to convert the image into an ASCII art string.

I believe there must be more appropriate identifiers, such as `extract_frame()` and `ascii_generator()`.

**Comment by PinkNekoFist** [comment]
nice idea, thx bro

**Comment by PinkNekoFist** [comment]
fixed
